{% set name = "embree" %}
{% set version = "3.13.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz  # [unix]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x86_64.linux.tar.gz  # [linux64]
  sha256: 8142c1fa0e8e89e279581e873f558b008a3d49b9b1e0091393e50377bcc52639  # [linux64]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x86_64.macosx.zip  # [osx]
  sha256: 6e9442e516cd54c2e7f6454c90fb8cda5721d76a14d29880ffa387820a486762  # [osx]
  fn: {{ name }}-{{ version }}.zip  # [win]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x64.vc14.windows.zip  # [win]
  sha256: 76570583a3d3e78f74b3cde2b0bbff8b0cc527959cc68b9e501b295e3aa7a960  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [aarch64 or ppc64le]

requirements:
  build:
    - python  # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libembree.so"  # [linux]
    - test -f "${PREFIX}/lib/libembree.dylib"  # [osx]

about:
  home: https://embree.github.io/
  license: Apache 2.0
  license_file: doc/LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - scopatz
    - Xarthisius
